spring.application.name=chatbot

server.port=8081

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-mini

gemini.api-key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/openai
gemini.api.model.name=gemini-2.5-flash
gemini.api.completions.path=/chat/completions

spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot
spring.datasource.username=postgres
spring.datasource.password=akshit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
