spring.application.name=chatbot
# Render provides the PORT variable; we use 8081 as a fallback for local dev
server.port=${PORT:8081}

# AI Configurations
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-mini
gemini.api-key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/openai
gemini.api.model.name=gemini-2.5-flash
gemini.api.completions.path=/chat/completions

# Database - Environment variables provided by Render's Postgres instance
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false